### ISSUE TITLE
[Feature request] display units

### ISSUE THREAD

**Issue by FrostKiwi** [georgealways/lil-gui#108]
I would love to display what units the current value has, that's being changed, instead of writing it in parentheses with `.name()` For instance, here is an example with pixels (px):
![image](https://github.com/georgealways/lil-gui/assets/60887273/82036327-0354-426b-b18c-7b9003214f1a)
Ideally the unit should have a different font color to signify, that you are changing the value, not the unit.

**Comment by georgealways** [comment]
I'm going to mark this wontfix for reasons similar to #110.

There's a fair bit of DOM involved in making a "suffix" for an input field like that. I think having to write (px) in a label is a worthy trade off in terms of file size and code complexity.
