### ISSUE TITLE
[Feature request] labels

### ISSUE THREAD

**Issue by FrostKiwi** [georgealways/lil-gui#110]
It would be nice to comment on the meaning of a folder by adding a short piece of text.
Here is the GUI in WebApp created with https://github.com/Immediate-Mode-UI/Nuklear. There I like to explain a settings section with a label, a short piece of text.
![image](https://github.com/georgealways/lil-gui/assets/60887273/70085bfd-6196-4b96-be3c-2c2ff42339af)

**Comment by georgealways** [comment]
Hi there—I agree it would be nice but probably won't be added. I think it's great when we expose these panels to users, but the primary use-case for lil-gui is developer-facing debug. The library's at a point where I don't want it to grow much larger unless it's in service of that goal. 

It's easy to imagine code in user-land that appends and styles DOM for these sort of info boxes, i.e. `folder.$children.prepend(myInfoText)`. Someone could even write a library that extends GUI with methods for adding those / applying the relevant CSS vars, etc :)
