### ISSUE TITLE
Folder Toggle Functionality Not Working Properly

### ISSUE THREAD

**Issue by JoeyQiao6** [georgealways/lil-gui#113]
I'm encountering an issue with the folder and control toggle functionality in lil-gui. It seems like there are two layers of panels. The outermost panel appears to work as expected, but the inner panel does not. When I try to click to toggle the folder, it shows the collapsing animation but doesn't actually collapse.

Would appreciate any guidance or fixes for this issue. Thank you!

https://github.com/georgealways/lil-gui/assets/96880446/634ff383-3e29-439f-8b98-ebb10f75175f

**Comment by georgealways** [comment]
Hi! Seems like you may be creating the same GUI twice? By default they're `position: fixed`, so they'll go on top of each other if more than one are created.

**Comment by JoeyQiao6** [comment]
Thank you very much for your answers. I found the reason; it's because React's StrictMode intentionally triggers double rendering in development mode to detect side effects. Thank you very much.
