### ISSUE TITLE
gui.reset error: Uncaught TypeError: t.match is not a function

### ISSUE THREAD

**Issue by q479360791** [georgealways/lil-gui#114]
hello!
run gui.reset error  at color format: 'transparent' and rgba(x,x,x,x) 

```
const gui = new GUI();
  let obj = {
    color1: '#AA00FF', 
    color2: 'transparent', //reset error: t.match is not a
    color3: 'rgba(255, 218, 86, 0.6)', //reset error: t.match is not a
    func: () => gui.reset(true)
  }
  gui.addColor( obj, 'color1' );
  gui.addColor( obj, 'color2' );
  gui.addColor( obj, 'color3' );
  gui.add( obj, 'func' );
```

error at:
src/utils/normalizeColorString.js

**Comment by georgealways** [comment]
Hi there—the library doesn't support colors with transparency. The list of supported color formats is here: https://lil-gui.georgealways.com/#Guide#Colors

**Comment by q479360791** [comment]
> Hi there—the library doesn't support colors with transparency. The list of supported color formats is here: https://lil-gui.georgealways.com/#Guide#Colors

ok, thanks
Do you have a plan?

**Comment by georgealways** [comment]
It's not likely to be added to the core library: see #19
