### ISSUE TITLE
Astro + lil-gui leads an error during build

### ISSUE THREAD

**Issue by raulfdm** [georgealways/lil-gui#115]
Hey peps, I hope you're good 👋 

I'm building Astro's website with three.js + lil-gui and I noticed that during the build, Astro had a hard time compiling/optimizing `lil-gui` dependency.

I know it might be a problem for Astro's folks (and I've reported it here https://github.com/withastro/astro/issues/8660) but I notice that this problem goes away when we define the `exports` property in `lil-gui`'s package.json:

https://github.com/georgealways/lil-gui/assets/12464600/b4b4aa40-9790-469a-a36b-e87cfda3b424

I was wondering if you're willing to add exports to support modern module resolutions. It won't change anything for past node versions because `main` and `module` will remain there, it'll be just an addition.

Here are some references:

- https://nodejs.org/api/packages.html#exports-sugar
- https://webpack.js.org/guides/package-exports/

### System:
 - OS: macOS 14.0
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 444.56 MB / 32.00 GB
 - Shell: 5.9 - /bin/zsh
### Binaries:
 - Node: 18.15.0
 - pnpm: 8.7.5
### Dependencies
 - lil-gui: 0.18.2

**Comment by georgealways** [comment]
Hey there, thanks for the detailed report! So we actually have this fix merged (#111) and waiting on the dev branch for the next release. So, coming soon :)

**Comment by raulfdm** [comment]
Nice @georgealways ... thanks for letting me know 🙏

**Comment by georgealways** [comment]
The `exports` field is included in package.json as of 0.19.0, cc & ty @jonobr1

**Comment by jonobr1** [comment]
No, thank you!
