### ISSUE TITLE
Dropdown search (input completions)

### ISSUE THREAD

**Issue by zardoy** [georgealways/lil-gui#116]
I have a very large number of options, what do you think of implementing search input along with dropdown? Currently the easiest solution I think would be to provide input with datalist with a some option enabled

**Comment by georgealways** [comment]
Hey thanks for submitting an issue. The goal is to keep lil-gui small, so I think that's probably out of scope for the core library. Maybe it can be developed as a third party add-on.

**Comment by zardoy** [comment]
Another use case that might be useful but not possible now is to have some suggestions for string inputs. Btw thanks for quick response
