### ISSUE TITLE
Minor issue: cursor style over checkbox

### ISSUE THREAD

**Issue by Peque** [georgealways/lil-gui#13]
It seems the cursor is displayed as a pointer when hovering the right section of the checkbox. That is fine since the whole section is used to activate/deactivate the checkbox.

However, when hovering right over the checkbox, the cursor is displayed with the default style.

Hope you can reproduce it. I can with both Firefox and Chromium. :blush:

**Comment by georgealways** [comment]
you are correct, good catch! there's a few little css fixes on my list and i'll add that as well

**Comment by awelles** [comment]
In case it's helpful, this mod to line 43 in controllers.scss seems to fix that:

```
-       .controller.boolean .widget {
+       .controller.boolean .widget, input[type='checkbox'] {
                cursor: pointer;
        }
```
