### ISSUE TITLE
Feature request: input spinner

### ISSUE THREAD

**Issue by Pickleheaded** [georgealways/lil-gui#134]
Would it be possible to add an input spinner to lil-gui as per bootstrap-input-spinner [https://shaack.com/projekte/bootstrap-input-spinner/](url) ?

For me, I believe most bases are covered in lil-gui and that this would be a great feature to have.

If you feel that this should be a custom controller, please could I request some information on creating custom controllers for lil-gui and when I have some free time I will try and create this controller.

Many Thanks!

**Comment by georgealways** [comment]
Hi there, I'll consider it!

For now I would suggest adding your own button elements to `controller.$widget` that call `controller.setValue`.
