### ISSUE TITLE
Allow dot notation in property name

### ISSUE THREAD

**Issue by mistic100** [georgealways/lil-gui#143]
Hi

I think it woud be a good addition to allow the dot notation in the property name to allow using nested objects in controllers.

**Example:** 

```js
const config = {
  center: { x: 807, y: 607 },
};

const gui = new GUI();

gui.add(config, 'center.x', 0, 1200);
gui.add(config, 'center.y', 0, 800);
```

**Risks:**

If someone has property names using a dot, it will break.

```js
const config = {
    'center.x': 807,
}
```

But who does that...

**Alternatives:**

In my case I can add getters and setters, but it is not always possible if the controller is a existing object from and external library or whatever.

```js
const config = {
    center: { x: 807, y: 607 },

    get x() {
        return this.center.x;
    },
    set x(x) {
        this.center.x = x;
    },
};
```

Thank you

**Comment by mistic100** [comment]
I am dumb :-)

```js
gui.add(config.center, 'x', 0, 1200);
gui.add(config.center, 'y', 0, 800);
```

Thanks for the lib !

**Comment by georgealways** [comment]
Not all—glad you figured it out!
