### ISSUE TITLE
Drag-Controls without min/max values

### ISSUE THREAD

**Issue by GniLudio** [georgealways/lil-gui#145]
It would be nice if the number field could have drag-controls without a minimum and maximum value.

## Version 1
Allow the name next to the default number field to be dragged when `step` is set.

## Version 2
Add two new parameter `dragStart` and `dragEnd` that can be used instead of `min` and `max`.
When dragging the mouse over the edge, the value keeps increasing/decreasing, but the value isn't limited to specified range.

**Comment by georgealways** [comment]
You should already be able to drag the field for number controllers, even if they don't have min & max. If you can't drag the fields in the first panel [here](https://lil-gui.georgealways.com/examples/kitchen-sink/), let me know what browser and OS you're using.

**Comment by GniLudio** [comment]
> You should already be able to drag the field for number controllers, even if they don't have min & max. If you can't drag the fields in the first panel [here](https://lil-gui.georgealways.com/examples/kitchen-sink/), let me know what browser and OS you're using.

I always only tried horizontal dragging (like the slider), but now realized that the normal number field allows vertical dragging.
Thanks for your help.
