### ISSUE TITLE
auto step issuse

### ISSUE THREAD

**Issue by z2586300277** [georgealways/lil-gui#147]
Why does dat.gui automatically set step without setting step, while lil.gui's step is always 1

**Comment by z2586300277** [comment]
folder.add( { key: 1 },  'key' )

**Comment by georgealways** [comment]
If you don't specify a step, lil-gui sets it to 0.1 or 0.1% of the range between min and max. But I'm not sure exactly what your question is.

**Comment by z2586300277** [comment]
if me not set min and max ，sample folder.add( { key: 1 }, 'key' ), dat.guI can auto set step,but lil guide can't ,it always 1

**Comment by z2586300277** [comment]
if me not set min and max ，sample folder.add( { key: 1 }, 'key' ), dat.guI can auto set step,but lil guide can't ,it always 1

**Comment by georgealways** [comment]
What are you expecting step to be in this case for lil-gui?

**Comment by z2586300277** [comment]
I hope it can implement a dynamic step, or based on initial values such as 1step 0.1, 0.1 step 0.01, or dynamically change the accuracy according to the user's modified range, or add an accuracy input box

**Comment by georgealways** [comment]
Got it. If I remember, in dat.gui, if there was no min/max, we set the step based on the magnitude of the initial value. Maybe that's what you mean by dynamic step? That behavior was a bit too magical in my opinion.

If there's no step specified, the intent is:
- Number box dragging increments by 0.1 per pixel
- One arrow key === +/- 1

Step is already calculated "dynamically" if min and max are provided.
