### ISSUE TITLE
Build fails on Windows: Could not load dist/lil-gui.css

### ISSUE THREAD

**Issue by georgealways** [georgealways/lil-gui#17]
Full error below:
![image](https://user-images.githubusercontent.com/7141218/142629123-f487a732-4da7-4ac5-8fdf-12a67461b672.png)

_Originally posted by @Slynchy in https://github.com/georgealways/lil-gui/issues/15#issuecomment-974064417_

**Comment by georgealways** [comment]
Just to be sure rollup isn't being crazy, `dist/lil-gui.css` truly doesn't exist, right?

If you do `npm run sass` by itself, does any CSS appear in dist?

If not (and I'd be confused if this worked), I wonder if it's the package_config variables. Try `npx sass style/index.scss howcouldthisbe.css --no-source-map --no-charset` and see if anything comes out.

**Comment by Slynchy** [comment]
🤷‍♂️ 

![image](https://user-images.githubusercontent.com/7141218/142662880-07f92ba5-14db-49d1-b57f-5faf4632a095.png)

**Comment by georgealways** [comment]
Aha—so it actually is the `package_config` vars, Windows wants them in a [slightly different format](https://stackoverflow.com/questions/42166632/how-to-use-npm-config-variables-cross-platform-win-linux). There's a library to deal with this, but I'd rather just swap those vars out for their values in package.json. 

This will be in the next release—for now, in package.json, replace: 

`$npm_package_config_style` with `dist/lil-gui.css` 
`$npm_package_config_styleMin` with `dist/lil-gui.min.css`

and the build should work.

**Comment by Slynchy** [comment]
Yup, that works for now 👍 cheers!

**Comment by georgealways** [comment]
Glad to hear it -- and that's been changed in package.json as of #18
