### ISSUE TITLE
Question: Should lil-gui stop propagation of key events when inputing values?

### ISSUE THREAD

**Issue by Peque** [georgealways/lil-gui#22]
The case is well-described here for dat.gui and applies for lil-gui as well:

https://stackoverflow.com/questions/67769713/avoid-propagating-keydown-events-from-dat-gui-to-three-js-scene

When editing an input field, key events get propagated. There is an easy workaround as stated in the StackOverflow thread, but maybe it should be handled by lil-gui?

The example shown in the question does not make much sense, but a real use case is the following:

- The user can select objects in the scene
- The user can remove objects in the scene pressing `DEL`
- The user can edit parameters of the object in lil-gui
- If the user edits a parameter (i.e.: change a numerical number with the keyboard) and decides to delete the current value by pressing `DEL` instead of backspace, the object will be deleted from the scene, which is unexpected

**Comment by georgealways** [comment]
Hm, yes that can be annoying. I'll have to think about whether that belongs in user-land though. The library solution would be calling `e.stopPropagation()` on keydown and keyup for the number input and the color input.

**Comment by georgealways** [comment]
As of 0.15, the `input` elements in the number, string and color controllers all call `e.stopPropagation()` on keyup and keydown.
