### ISSUE TITLE
How to change default theme?

### ISSUE THREAD

**Issue by Peque** [georgealways/lil-gui#23]
This is probably due to my lack of JS experience, but I am unsure about how should I change the CSS style of the default theme. Note that I would like to change it once, not dynamically.

I tried to create a simple GUI with red background, but I am of course doing something wrong:

```js
import { GUI } from 'https://cdn.skypack.dev/lil-gui';

const root = document.documentElement;
root.style.setProperty('--background-color', '#ff0000');
root.style.setProperty('--title-background-color', '#ff0000');

const gui = new GUI();
gui.add( document, 'title' );
```

I guess I am setting the wrong property. :joy: 

Is `const style = Array.from( document.querySelectorAll( 'style' ) ).find( v => /lil-gui/.test( v.innerHTML ) );` and then replacing the `innerHTML` as in the [kitchen sink example](view-source:https://lil-gui.georgealways.com/examples/kitchen-sink/) the only/best way to do it?

If there is a way to change styles without iterating (i.e.: before instantiating the GUI elements), that would be great.

**Comment by awelles** [comment]
You could do something like this, but after you attach the GUI:

```js
import { GUI } from './lil-gui/lil-gui.esm.js';

let gui = new GUI();

document.styleSheets.item( 0 ).insertRule( '.lil-gui { background-color: red !important; }', 0 )
```

**Comment by awelles** [comment]
Recommenting, deleted my other somehow. One option is messing around with the document's styleSheet after attaching the GUI:

```js
import { GUI } from './lil-gui/lil-gui.esm.js';

let gui = new GUI();

document.styleSheets.item( 0 ).insertRule( 'div.lil-gui, div.root  { background-color: red }', 0 )
```
Or tweak a particular rule:

```ls
document.styleSheets[0].rules[0].style.backgroundColor = "red";
```

**Comment by georgealways** [comment]
The idea is that you would override lil-gui's default styles in a stylesheet somewhere on the page—I can't think of a great reason to set the CSS with JS.

Somewhere in your head tag:

```html
<style>
.lil-gui {
  --widget-color: blue;
}
</style>
```

lil-gui always inserts its stylesheet before any other CSS definitions, so yours will take priority.

**Comment by awelles** [comment]
@Peque FYI: If you must, this is more like what you were trying, but  *after* attaching the gui: 

```js
let gui = new GUI();

gui.domElement.style.setProperty( '--background-color', '#ff0000' );
gui.domElement.style.setProperty( '--title-background-color', '#ff0000' );
```

**Comment by Peque** [comment]
@awelles Thanks, that is exactly what I was looking for! :blush: 

Since I am creating multiple GUIs, I extended lil-gui's class like this:

```js
class GUI extends LilGUI {
    constructor(config) {
        super(config);
        this.domElement.style.setProperty( '--background-color', '#ff0000' );
        this.domElement.style.position = "absolute";
    }
}
```

@georgealways Yeah, I would normally use CSS rules on the page. In this case, however, the renderer and the GUI are part of a separate project. Let us say that what you do is "embed" (import) that project in a website (or multiple websites, actually). Instead of having to tweak the GUI style from the websites where you embed it, you set a default style directly in JS. Does that make more sense?

**Comment by georgealways** [comment]
Oh, I see—you just want it in one file for portability's sake. That's totally valid, lil-gui does the same thing internally after all.

The library [inserts style tags](https://github.com/georgealways/lil-gui/blob/master/src/utils/injectStyles.js) (as opposed to defining inline styles), which is nice because you can write CSS verbatim, use pseudo-selectors etc:

```js
injectStyles( `
.peque-gui:hover { 
   --background-color: red;
}` );
```

I'm considering exposing `injectStyles` as I write a custom controller guide.

**Comment by Peque** [comment]
I found one issue while [extending the class](https://github.com/georgealways/lil-gui/issues/23#issuecomment-980586948). When calling `.addFolder`, the method calls `new GUI`, which is effectively lil-gui's class instead of the extended class. So the folders have the default lil-gui's theme instead of the custom theme.

**Comment by georgealways** [comment]
Extending the GUI class isn't really something I had in mind. If you're only extending the GUI class to apply custom styles, I would still recommend doing what I described in my first comment: it seems just as much trouble to "embed" a CSS file as it would your custom JS class.

**Comment by georgealways** [comment]
Extending the GUI class isn't really something I had in mind. If you're only extending the GUI class to apply custom styles, I would still recommend doing what I described in my first comment: it seems just as much trouble to "embed" a CSS file as it would your custom JS class.
