### ISSUE TITLE
Feature request: color gradient controller

### ISSUE THREAD

**Issue by shawn0326** [georgealways/lil-gui#25]
It would be great to have a color gradient controller. I think this may be a common requirement, and few gui libraries can easily implement it.
Like this:
![68747470733a2f2f692e696d6775722e636f6d2f4b6641376874482e706e67](https://user-images.githubusercontent.com/2128275/144442443-63e1d8e1-613a-4da7-bf0d-ba72f40f21d9.png)

**Comment by georgealways** [comment]
That would be a useful controller, but it should probably be a user extension. I'm working on an example that demonstrates the process of making a custom controller and hope to have it done soon!
