### ISSUE TITLE
403 error in examples

### ISSUE THREAD

**Issue by Peque** [georgealways/lil-gui#3]
It seems examples are not accessible:

- https://lil-gui.georgealways.com/examples/basic/
- https://lil-gui.georgealways.com/examples/kitchen-sink/

![Screenshot from 2021-11-07 01-44-55](https://user-images.githubusercontent.com/526577/140628107-c62d16b3-61e3-4c7f-ad67-9f95dbee5964.png)

**Comment by georgealways** [comment]
uh oh! Strangely it's working for me but I think I know what caused this: I added some logic to the server to prevent hot-linking the built source and must have messed it up. I reverted that, so let me know if it's working now.

**Comment by Peque** [comment]
@georgealways Working now, thanks! :heart: 

I'll definitely have a deeper look into this project, looks great! :blush:
