### ISSUE TITLE
listen() halts UI if used on many controllers

### ISSUE THREAD

**Issue by yoavmil** [georgealways/lil-gui#35]
I've tried `lil-GUI` to replace `dat.GUI`, following `threejs`. 
I've noticed it kill my framerate. this happens because I use the `listen()` on each field.
Note that in `dat.GUI` it doesn't happen.
For now I'm returning to `dat`. keep me updated.

```ts
/*
In this code I populate the GUI with a settings structure. 
*/
  private populateGui(node: GUI, key: string, settings: any) {
    if (typeof settings[key] == typeof String()) {
      node.add(settings, key).listen();
    } else if (typeof settings[key] == typeof Number()) {
      node.add(settings, key).listen();
    } else if (typeof settings[key] == typeof Boolean()) {
      node.add(settings, key, settings[key]).listen();
    } else if (typeof settings[key] == typeof Object()) {
      let folder = node.addFolder(key);
      Object.keys(settings[key]).forEach((k) => {
        this.populateGui(folder, k, settings[key]);
      });
    }
    node.close();
  }

  public open(settings: Settings) {
    this.close();
    this.gui = new GUI();
    this.gui.domElement.parentElement.style.zIndex = "10";
    Object.keys(settings).forEach((key) => {
      this.populateGui(this.gui, key, settings);
    });
  }

```

**Comment by georgealways** [comment]
Oh thanks for the catch. Yes, dat.GUI consolidates all the listen loops, lil-gui makes a new loop for each controller. 

Is this hosted anywhere by chance? I'm curious how many controllers it takes to make this happen. 

I'll look into consolidating the loops in a future release.

**Comment by yoavmil** [comment]
not hosted. I had ~100 controllers. do you plan to solve it?
BTW, dat.gui has a npm warning , does lil-gui has it too?

``` 
dat.gui  *
Severity: high
Regular Expression Denial of Service in dat.gui - https://github.com/advisories/GHSA-chwr-hf3w-c984
No fix available
```

**Comment by georgealways** [comment]
Yes, I'd like to. I'll need to reproduce it first to have something to test against.

dat.gui's NPM warnings aren't related to this library. Unless you're seeing warnings when installing lil-gui you should be fine.

**Comment by georgealways** [comment]
Should be able to do a lot more listening if you update to 0.16.1

Let me know how that works!

**Comment by yoavmil** [comment]
No sir. Sorry, still way too slow. Down to 5 fps (!). And yes, I'm using 0.16.1

**Comment by georgealways** [comment]
I'm able to run this page https://dev.lil-gui.georgealways.com/examples/listen-stress/?100 at 50fps on a 2014 MBP (after checking animateAll). Unless you're able to upload your work I can't really help any further.
