### ISSUE TITLE
gui.remove is not a function

### ISSUE THREAD

**Issue by greggman** [georgealways/lil-gui#37]
Saw that a sample that was using dat.gui is failing with `gui.remove is not a function`

https://jsgist.org/?src=c7a46e2519f534df07f1be4f2a2fa35d

**Comment by georgealways** [comment]
Yes, that was an intentional API change, `gui.remove` is replaced by `controller.destroy()`. It didn't really make sense to me that you needed a reference to the parent GUI to do this. https://lil-gui.georgealways.com/#Migrating

I could see a world where `gui.remove` exists as a synonym to make the lib more "drop-in" complete. But there's a few other renames and API changes besides this one. It begs the question as to whether they should **all** be "forwarded" in some way (IMO probably not).

**Comment by greggman** [comment]
ugh, you can do what you want but you list the lil.gui as a drop in replacement. three.js dropped it in and it appeared to work but in actually tons of stuff is broken. If lil.gui is not a drop in replacement then please consider not advertising it as such

**Comment by greggman** [comment]
To be more helpful, just a suggestion, I'd suggest changing the readme from 

> Works as a drop-in replacement for dat.gui.

to something like

> Works similar to dat.gui (see below)
>
> ...
>
> ### Using lil.gui as a replacement for dat.gui
>
> You can use lil.gui as a replacement for dat.gui but you'll need to be aware of these changes
> 
> * remove ....
> * empty folders as labels ....
> * out of range values
> * accessing gui.__controllers directly
> * setEnable...  
> * etc....

**Comment by georgealways** [comment]
Sorry it broke things for you! I agree, some kind of "mostly" language could go in the "drop-in" sentence—I was just trying to keep it short.

I think the migrating section achieves what you're describing. It's pretty explicit about breaking changes, but perhaps it could be featured more prominently in the readme.

> For most projects, moving from dat.gui to lil-gui should be as simple as changing the import URL. The API is designed to be as backwards-compatible as is reasonably possible, but this section aims to address any breaking changes.

It is missing `__controllers => .controllers` though, thanks for pointing that out.

In general, I'm happy to share my reasoning behind any of the API or cosmetic changes.

**Comment by greggman** [comment]
I don't mind that the API changed. Rather, "drop in replacement for dat.GUI" effectively tells me "no need to read the docs if you already know dat.GUI because you can just drop it in and it all works"

**Comment by greggman** [comment]
Just random thinking out loud, not a judgement 😜

I don't know if `parent.remove(elem)` or `elem.destroy()` is a better API. I've done both in my life. But, one argument for `parent.remove(elem)` over `elem.destroy()` is the thing being modified is the parent's list of children, not the elem. The elem shouldn't be able to affect the parent. Further, you should arguably be able to do this

     gui1.remove(elem)
     gui2.add(elem)

I'm not suggesting you change it. The logic that it's convenient to be able to not have to have a reference to the parent is good too. The HTML DOM has both, `parent.removeChild(elem)` and `elem.remove()`

**Comment by georgealways** [comment]
Sure, let's put it back as a synonym for `destroy()`, there's valid arguments for both and it helps with compatibility.

I don't think `gui.add` should be overloaded to accommodate `gui.add( controller )` though. The added complexity doesn't feel justified given how simple it is to make a new controller. I don't think we put that in dat.gui either.

**Comment by georgealways** [comment]
I'm going to change this to a won't-fix. The dat.gui => lil-gui transition feels like it's just about done, and I think we've provided enough migration notes and legacy support to make the switch easy. Thanks for your feedback.
