### ISSUE TITLE
Problem integrating in nw.js app

### ISSUE THREAD

**Issue by SkyBladeCloud** [georgealways/lil-gui#39]
Nw.js is a development platform by Intel which allows application programmers to combine a nodejs backend with a HTML/CSS/JS frontend into a standalone app (similar to Electron):

https://nwjs.io/

In Nw.js, visible HTML interfaces don't usually use the default, global "window". Rather, the global window corresponds to an invisible, background object. This is an useful design choice for headless environments. However, it has 3 problems with lil-gui:

1 - By default, lil-gui will attempt to add itself to the global (invisible) document.
2 - By delfault, styles will be injected in the head of the global invisible document.
3 - Event listeners will be registered in the global invisible document as well.

The first couple of issues can be worked around by using lil-gui's already available constructor parameters:

1 - Setting a custom HTML node from a visible document in the Nw.js app works and lil-gui's frame shows up.
2 - Disabling default style injection and setting a custom CSS in the visible document works as well.

While these couple of workarounds show a perfectly visible lil-gui frame on my Nw.js app, it's non-functional due to the fact that its event listeners are still being registered in the default, global document.

Thus, I'd like to ask: would it be possible to provide an optional, custom window/document for lil-gui to use (for instance, as a constructor parameter), instead of the global one?

Thank you very much and kind regards,

~Sky

**Comment by georgealways** [comment]
Hi Sky, that all makes sense. I'm guessing that specifically it's the references to `window` and `document.body` in NumberController? I'm pretty sure that's the only place those appear outside of GUI's constructor (which it sounds like you're avoiding with the `container` parameter). 

Let me know if you can share any stack traces or line numbers, it would be nice if lil-gui worked in an environment like this.

**Comment by djmisterjon** [comment]
i get no issue to integrate in nwjs , but am confused because i cant see listeners in events registers from the dev tool in the SDK ! 
I can see all my custom listeners, and other libs listeners but not lil-gui listeners ! need more test to understand why ! 
![image](https://user-images.githubusercontent.com/24865815/151964882-9a8a2a42-828f-4c15-bd8b-09e23bac9d8a.png)
also i think it should a good idea to make listeners to passive as chromium warn !
![image](https://user-images.githubusercontent.com/24865815/151965337-9b2a325a-ec05-4019-9642-0c183ad3a3d1.png)
https://www.chromestatus.com/feature/5745543795965952

**Comment by georgealways** [comment]
@djmisterjon 

> I can see all my custom listeners, and other libs listeners but not lil-gui listeners !

I wonder if that's the same issue the original post is describing?

> In my case, root collide with my root css, and maybe more soon , we will see.

I'd like to keep the class names intuitive, for now I'd recommend that you make your `.root` selector more specific so it isn't applied to the panel. Let's keep discussion about this in #29.

**Comment by djmisterjon** [comment]
> @djmisterjon

> > Also i think it should a good idea to make listeners to passive as chromium warn.
> 
> I'm not able to reproduce these warnings in Chrome or Chromium. Is this specific to nw.js?
> 

no i think its related to when its injected inside a virtual dom like react.
https://codesandbox.io/s/musing-fermat-o1ecm

**Comment by georgealways** [comment]
@djmisterjon Yea, that's strange, I'm still not able to get those warnings to show up from your link. I actually can't make those event listeners passive because they need to call `preventDefault`—you can safely ignore those warnings.

**Comment by SkyBladeCloud** [comment]
Hello all,

Thank you very much for your support and sorry for the late answer.

I do believe those "addEventListener" calls within NumberController are the cause of my issue. I don't have the means to build the library to test myself (yet), but as mentioned in my original post, "window" is a completely different entity in the context of a NW.js application...

...At least by default. I've found that NW.js does provide a feature to "merge" the default backend "window" with the frontend one, using the so-called "mixed context mode"

https://docs.nwjs.io/en/latest/For%20Users/Advanced/JavaScript%20Contexts%20in%20NW.js/#mixed-context-mode

In this mode, "window" is what lil-gui expect and the library works flawlessly for my use cases. However, mixed context has some drawbacks and for now I'm considering it a workaround in my application. I wonder if this is how @djmisterjon got the lib working on his environment, or if he uses another way I'm not aware of.

I'll do some further test, see if I can build the library and provide further insight.

Thanks again and kind regards,

~Sky

**Comment by georgealways** [comment]
Thanks for all the extra detail Sky. Ultimately though, I think this is the sort of thing that should stay in your fork. Abstracting every reference to window or document will make development harder going forward. I think the library should operate under the assumption that basic browser things like `document` or `requestAnimationFrame` exist and work.
