### ISSUE TITLE
gui.hide/show

### ISSUE THREAD

**Issue by Peque** [georgealways/lil-gui#4]
According to [the documentation](https://lil-gui.georgealways.com/#), `gui.hide/show` were removed.

Is there a way to hide/show the GUI instead, or is it a planned/supported feature?

**Comment by georgealways** [comment]
I could see it coming back in a future release. For anyone else looking, there's a little snippet in [this issue](https://github.com/georgealways/lil-gui/issues/6#issuecomment-962606925) that will get you the same functionality in the meantime.

**Comment by georgealways** [comment]
`gui.hide()` and `show()` are back in 0.16.0
