### ISSUE TITLE
Console warning : [Violation] Added non-passive event listener

### ISSUE THREAD

**Issue by lucasflorian** [georgealways/lil-gui#41]
Hi,

There is warnings in the console because of the `touchstart` and `wheel` events added to the inputs without the `{passive: false}` option.
This can be inconvenient when adding multiple properties because the console is full of warning and the other warnings are lost in the mass.

Console warning: 
`[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive.`

Sources of the warnings : 

```
this.$input.addEventListener( 'wheel', onWheel );
this.$title.addEventListener( 'touchstart', () => { } );
this.$slider.addEventListener( 'touchstart', onTouchStart );
this.$slider.addEventListener( 'wheel', onWheel );
```

I'm using the latest version (0.16.0)

**Comment by snetsrac** [comment]
I'm getting them on Chrome Version 98.0.4758.82. I'm currently seeing 40 of these warnings on page load at [https://lil-gui.georgealways.com/](https://lil-gui.georgealways.com/).

Here's an example:
`lil-gui.esm.js:1770 [Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952`

And one of these:
`[Violation] Forced reflow while executing JavaScript took 36ms`

See [https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md). I'm not getting any scroll lag or stuttering though, so it's mostly just the minor issue of shutting up the warnings.

**Comment by lucasflorian** [comment]
Hi George,

I'm getting the warnings on Chrome Version 97.0.4692.99.

**Comment by georgealways** [comment]
@lucasflorian Ah, okay thank you. So all I need to do is check "verbose". Checking that before hadn't worked for some reason.
