### ISSUE TITLE
Feature request: calendar controller

### ISSUE THREAD

**Issue by Peque** [georgealways/lil-gui#5]
It would be great to have a date/calendar input controller.

Something like:

![Screenshot from 2020-03-30 11-07-35](https://user-images.githubusercontent.com/526577/77895198-b6fd9180-7276-11ea-8796-b754660443e2.png)

**Comment by georgealways** [comment]
No plans to add a date/calendar input right now, but at some point I'm hoping to put together a good example of what it's like to extend the library with your own controller type.
