### ISSUE TITLE
Don't disappear in react

### ISSUE THREAD

**Issue by pikooli** [georgealways/lil-gui#52]
Hello, i try to use it in my nextjs website.

But i go int a problem.

When i navigate to another page and go back to the one with the lil-gui, it create another gui over the existing one.
And when you switch page, the gui don't disapear.
I think it a problem with document, like the gui is attached to the document but in react the document don't change so the gui alway stay.

I try to remove it but i didn't find a way.

Code look like this : 
```
const [gui, setGrui] = useState<any>();
  const [state, setState] = useState({
    sunGrid: false,
    earthGrid: false,
    moonGrid: false,
  });

  const myObject = {
    sungrid: () => setState((prev) => ({ ...prev, sunGrid: !prev.sunGrid })),
    earthgrid: () =>
      setState((prev) => ({ ...prev, earthGrid: !prev.earthGrid })),
    moongrid: () => setState((prev) => ({ ...prev, moonGrid: !prev.moonGrid })),
  };

  useEffect(() => {
    if (!gui) setGrui(new GUI());
  }, []);

  useEffect(() => {
    if (gui) {
      gui.add(myObject, "sungrid");
      gui.add(myObject, "earthgrid");
      gui.add(myObject, "moongrid");
    }
  }, [gui]);
```

Thanks a lot

**Comment by georgealways** [comment]
I haven't used this library, but it doesn't sound like the page is being "switched" in the literal sense. I can't speak to how `useEffect` works, but you can use `gui.destroy()` to remove the GUI when the user "navigates".

**Comment by pikooli** [comment]
gui.destroy() work, thank you
