### ISSUE TITLE
e.stopPropagation() on $widget ? where is events ref ?

### ISSUE THREAD

**Issue by djmisterjon** [georgealways/lil-gui#53]
How can we access to listener binder to $widget ? 
![image](https://user-images.githubusercontent.com/24865815/163055548-43d7a48e-db61-4ee0-8c02-d32b4fb4a752.png)

Let say i want add a DND for the GUI window width position relative.
But i dont want allow drag the GUI if the mouse is on a $widget.

Best solution will be add  a `e.stopPropagation()` on all widget ? 
But i cant found a ref of $widget events

So when i drag in a $widget, the GUI also drag.

---

EDIT:
https://github.com/georgealways/lil-gui/blob/d3c2bfdbd2b49cf9f940b7cd6890022ec20b7c18/src/NumberController.js#L211

Hum, this is not good ? what happen if we destroy the gui ? how do you clean listener ? 
why not directly asign event to dom ? 
```js
// this.$input.addEventListener( 'input', onInput ); // this is usually for global usage , and make hard to manage.
this.$input.oninput = onInput;
// or if context needed
this.$input.oninput = (...arg)=> onInput(...arg);

```

**Comment by djmisterjon** [comment]
okey forget me i found a way
```js
		c.$widget.onpointerdown = ( e )=>{
				e.stopPropagation();
				e.preventDefault();
				e.stopImmediatePropagation();
			};
```

but i will keep open, because i am worry about how you destroy event listener  to avoid memory leak ? 
if you have time to point me where is your destroy handler plz in the source code ?
 thanks

**Comment by georgealways** [comment]
I'm glad you found a workaround—right now, the GUI only stops event propagation on `keyup` and `keydown` to avoid conflicts with global key commands.

As for destroying event listeners: it's enough to just remove the DOM elements from the page. You don't have to worry about memory leaks, the browser takes care of this automatically.

**Comment by djmisterjon** [comment]
> 

thanks your for your time :)
