### ISSUE TITLE
Value are sometimes not round

### ISSUE THREAD

**Issue by GauthierEd** [georgealways/lil-gui#56]
Sometimes the values inside the gui are not round, you can see at the screen
![Capture](https://user-images.githubusercontent.com/73186172/170005844-23e9c2e1-e112-4ee2-9e6b-202dd267f16a.PNG)

**Comment by georgealways** [comment]
Ah, thank you—that shouldn't happen.

Can you show me the code you used to create that controller? What are the min/max or step values?

**Comment by HarlausG** [comment]
![Capture](https://user-images.githubusercontent.com/73186172/170287269-7e0c6515-f788-4b7e-88b5-07a24bfff51c.PNG)

**Comment by georgealways** [comment]
Could you also console.log `objet.degressitive` right before that line and tell me the value? merci!

**Comment by HarlausG** [comment]
with console.log, i get the same value : 30.0000000000004

**Comment by georgealways** [comment]
Ohh, okay—and I assume it's rounding correctly once you start using the slider?

If so, then this is actually the intended behavior. Right now, number controllers always show every decimal place, and they don't round values when they're created. This way, your code behaves the same whether the GUI is created or not.

If the number is going into the GUI with all those extra decimals, then that's the way it will be displayed. (If the GUI showed `30` you might be really confused when `objet.degrssitive === 30` evaluates to false.)
