### ISSUE TITLE
 Multiple controllers on same row ? 

### ISSUE THREAD

**Issue by kasra0** [georgealways/lil-gui#58]
Hi,

I would like to know if this is implemented or planned to be implemented?
I checked the documentation  I did not see anything about this topic.

If it's not implemented, let's say that I want to have 2 checkboxes and 2 buttons on the same row,
I have to create elements programmatically with the right CSS and then add them to the gui, is that correct ?

Thanks for your help.

**Comment by georgealways** [comment]
Hi there—there isn't a plan to support custom layouts like that. However, we have been talking for a while about an API for writing custom controllers, which could have as many UI elements as you'd like. 

For now you can always write your own CSS to change a controller's appearance, or if you're feeling really hacky, you can add DOM elements to a controller's `$widget` element. 

If you don't mind sharing, I'm curious to know what sort of values you'd be controlling with that?

**Comment by kasra0** [comment]
I will do a quick dirty hacky example.

Actually, when I said  _let's say that I want to have 2 checkboxes and 2 buttons on the same row_  it was just a hypothesis.

Being able to create multiple controllers on the same row is another way of clustering in less space.
We could create for example grid of buttons and so on...It becomes obvious when we need a lot of switches for testing all possible states. It's common to have 5,6,7 switches for a command. If you want to test a few commands, then your GUI becomes long for nothing.
On the same topic, the Tabular component would be great too.
Testing the maximum of possibilities with the least possible space ( ... and time ?  ;-) ) 

Thanks a lot for your work!

**Comment by kasra0** [comment]
As the add function returns either a : 

- OptionController
- NumberController
- BooleanController
- StringController
- FunctionController

If I want to create a group of buttons in a row I have to first create a controller ( head ) to be able to get the  $widget property.
Then we can add the other functions ( tail ).

this code is working, but it's a dirty hack :

```
const head = {f0:()=>console.log("f0") }
const tail = {
  f1:()=>console.log("f1"),
  f2:()=>console.log("f2"),
  f3:()=>console.log("f3"),
  f4:()=>console.log("f4"),
}
function createButton(key,value){
  const b        =  document.createElement("button")
  b.onclick      =  value
  const d        =  document.createElement("div")
  d.textContent  =  key    
  b.appendChild(d);
  return b 
}
function buttonGroup(head,tail){
  gui.add(head,Object.keys(head)[0])
  const controller =  gui.controllers[gui.controllers.length-1]
  Object.entries(tail)
  .map(([key,value])=>createButton(key,value))
  .map(x=>controller['$widget'].appendChild(x))
}
```

**Comment by georgealways** [comment]
Thanks for putting this together. Agreed, the above is hacky, but ultimately I don't see a feature like this making it into the library. I think part of the appeal of the lil/dat-gui API is the "no-layout" philosophy, i.e. "I don't want to think about where this controller goes or what it looks like". Having multiple buttons in a row seems straightforward, but the approach falls apart when it comes to the other controllers that all have external labels.
