### ISSUE TITLE
Step is ignored when typing a number

### ISSUE THREAD

**Issue by Peque** [georgealways/lil-gui#62]
If you currently define a number controller with step `1` (i.e.: integer), then when moving the scroll bar the value gets adjusted to an actual integer. However, if you go to the number input field and enter `1.234`, then after `onFinishChange` this value will be stored internally.

Would it make sense to "snap" the value to the given step always? In example, if you input `1.234` and the step is `1`, the value would be rounded to `1`.

This could apply to any step, not just integer steps (i.e.: with step `0.1` and value `1.234`, it could be rounded to `1.2`). But with integers it makes even more sense, since you may want to "ensure" the value is an actual integer (i.e.: imagine you used that number to access a position in an array).

**Comment by Peque** [comment]
PS: note how, if you input an invalid number that is above the maximum allowed number, it will be automatically snapped/adjusted. For example, you may input `100` for a controller that has its maximum defined as `4`. Once you un-focus the controller (i.e.: `onFinishChange`), the value is set to `4`, not `100`.

So basically, the controller is changing your manually-input value to comply with the rules of the controller. Perhaps what I am stating here is also a rule that the controller should comply and adjust to (the step). :blush:

**Comment by georgealways** [comment]
So that actually was my original intent: if you're going to type in numbers manually, then I'll let you put in whatever increment you want.

You make a totally valid point though—if the number controller lets you break step when typing, maybe it should let you break min and max as well. Or maybe they should both be enforced always. I don't have a strong opinion yet.

**Comment by Peque** [comment]
@georgealways I understand. :+1: 

I think I prefer when rules are enforced. Note how other kinds of rules are enforced too. For instance, you cannot input a string value in a number controller. To me, enforcing all rules defined in the code makes more sense. :blush:

**Comment by georgealways** [comment]
Fixed in 0.17.0
