### ISSUE TITLE
folders open and close events

### ISSUE THREAD

**Issue by FractalHQ** [georgealways/lil-gui#67]
Hey there!  I'm trying to keep track of the folder fold state to persist it in localStorage- what would the best way to accomplish that at the moment?

I noticed issues like #57 and would like to +1 for folder events 🙏

Something like `gui.folders.onChange()` would be sweet!

**Comment by georgealways** [comment]
Hey—not a clean way to do that at the moment, but that's a reasonable request. The old "preset" feature of dat.gui actually used to keep track of folder open/close state.

For now, you can use a hack like this. It essentially makes an "on create" hook for GUIs, then redefines the `_closed` property in a way you can observe.

```js
import GUI from "https://cdn.skypack.dev/lil-gui@0.17.0";

// GUI.title is called in GUI's constructor.
// You can piggyback off this to hack in an "on create" hook for GUI's.
const title = GUI.prototype.title;

GUI.prototype.title = function (...args) {
  
  // Do the old title behavior
  title.apply(this, args);
  
  // Redefine the "_closed" property for this GUI
  // in a way that lets us observe changes.
  let closed = this._closed;
  Object.defineProperty(this, "_closed", {
    get() {
      return closed;
    },
    set(v) {
      closed = v;
      console.log("Folder changed closed state", closed, this);
    }
  });
  
};

new GUI().addFolder();

```

That's also [here](https://codepen.io/georgealways/pen/dymXMey?editors=0010) as a codepen. @Pickleheaded — the above is probably a better solution for you as well for the time being. 

That said, I'm having trouble imagining a "real" way to do this elegantly. If we stick to the pattern we've used for events, we're talking about something like `gui.onFoldersOpenOrClose( fn )`, which isn't the prettiest. Maybe you guys can help me think of a better signature.

**Comment by FractalHQ** [comment]
Awesome!  Thanks for the help :).  That should be more than enough 🙏

I have a preset manager plugin for lil-gui that lets you pass in an instance and adds a preset manager with:
```ts
addPresetManager(gui, settings)
```
<img width="275" alt="Screenshot 2022-07-10 at 11 08 58 AM" src="https://user-images.githubusercontent.com/55504972/178150806-87d0e6c3-01c9-43a1-9ccf-1c152c09b733.png">

So this will be a great addition!

Perhaps the event could be `gui.onFolderToggle` or `gui.onFolderChange`?

**Comment by georgealways** [comment]
> Then I overrode the default open() and close() to set this.closed appropriately and call the callback if it was defined. 

@jxtplatinum Nice, that's not too different from what I'm doing above. The only reason that wouldn't work the same with lil-gui is you're actually calling `openAnimated` under the hood when you click a folder title.

> Perhaps the event could be gui.onFolderToggle or gui.onFolderChange?

@FractalHQ I'm leaning towards something like `gui.onOpenClose`, I'm not sure "change" or "toggle" gets the idea across. The signature I'm imagining looks like this:

```js
gui.onOpenClose( function( gui, open ) {

} );
```

... where `gui` is the folder that was opened or closed, and `open` is a boolean. I imagine these would bubble upwards, meaning if I defined an `onOpenClose` handler for the root GUI, it would fire if I collapsed the root GUI or any of its descendant folders. That's why I'm thinking `gui` comes before `open`.

**Comment by georgealways** [comment]
`gui.onOpenClose` is in as of 0.18, but the signature is slightly different than what I have above: **there's no `open` parameter**. It felt extraneous since you already have access to that information via `gui._closed`. The snippet from the docs is more helpful:

```js
gui.onOpenClose( changedGUI => {
    console.log( changedGUI._closed );
} );
```

Let me know how this works!

**Comment by jxtplatinum** [comment]
On Feb 11, 2023, at 9:15 AM, georgealways ***@***.***> wrote:
> 
> 
> gui.onOpenClose is in as of 0.18, but the signature is slightly different than what I have above: there's no open parameter. It felt extraneous since you already have access to that information via gui._closed. The snippet from the docs is more helpful:
> 
> gui.onOpenClose( changedGUI => {
>     console.log( changedGUI._closed );
> } );
> Let me know how this works!
> 

Awesome. Thanks for the update. I’ll try it later this week and get back to you. Thanks.

**Comment by jxtplatinum** [comment]
On Feb 13, 2023, at 10:26 AM, Johnny Tolliver ***@***.***> wrote:
> 
> Awesome. Thanks for the update. I’ll try it later this week and get back to you. Thanks.

By the way, do you have a handy list of other changes between 0.17 and 0.18? Thanks.

**Comment by georgealways** [comment]
sure, that's here: https://github.com/georgealways/lil-gui/blob/master/Changelog.md#0180
