### ISSUE TITLE
HDR color

### ISSUE THREAD

**Issue by liuyug** [georgealways/lil-gui#70]
The model with emissive color that use HDR color space.

lil-gui could not identity HDR color.

**Comment by georgealways** [comment]
Hey there—currently there's no plan to support HDR color. Something like that would probably belong in a third-party plugin because a custom color controller would make the library a lot bigger. Alternatively, you could pair a normal SDR color with an intensity slider.

**Comment by georgealways** [comment]
Hey there—currently there's no plan to support HDR color. Something like that would probably belong in a third-party plugin because a custom color controller would make the library a lot bigger. Alternatively, you could pair a normal SDR color with an intensity slider.

**Comment by liuyug** [comment]
I find a page with the solution.  https://answers.unity.com/questions/1652854/how-to-get-set-hdr-color-intensity.html
