### ISSUE TITLE
[idea] Shorter syntax

### ISSUE THREAD

**Issue by remmel** [georgealways/lil-gui#73]
Hi!

I was thinking about a shorter syntax to bind (one-way) a gui checkbox to a property; do you think to another alternative?
When clicking on the gui checkbox I want to update `obj.prop` and `obj.prop2` and make sure that the Gui is initied with right value.

# Solution 0

```js
const gui = new GUI();

const myObject = {
	Labl: obj.prop,
        get Labl2() { return obj.prop2}, set Labl2(v) { obj.prop2 = v}, //using setter and getter
};

gui.add( myObject, 'Labl' ).onChange(v => obj.prop = v)
gui.add( myObject, 'Labl2' )
```

# Solution 1
```js
export function guiAddAll(gui, params) {
    const paramsSmart = {}
    for (const param in params) {
        let [obj, prop] = params[param]
        paramsSmart[param] = obj[prop]
        gui.add(paramsSmart, param).onChange(v => obj[prop] = v)
    }
}
```

```js
guiAddAll(new GUI(), {
  Labl: [obj, 'prop'],
  Labl2: [obj, 'prop2']
})
```

# Solution 2
```js
export function guiAddOne(gui, label, obj, f) {
    const objAndPropName = f.toString().replace(/[ |\(\)=>]/g,'') // "obj.prop"
    const propName = objAndPropName.substring(objAndPropName.indexOf('.') + 1) // "prop"
    gui.params = gui.params ?? {} //init
    gui.params[label] = obj[propName] //gui.params = {"Labl": obj.prop}
    gui.add(gui.params, label).onChange(v => obj[propName] = v)
}
```

```js
guiAddOne(gui, 'Labl', obj, () => obj.prop)
guiAddOne(gui, 'Labl1', obj, () => obj.prop1)
```

Inspired from https://java2blog.com/get-variable-name-as-string-javascript/#Using_toString_method

# Other Solution ?
Maybe using Reflect API? Generate setter and getter in a loop?

**Comment by georgealways** [comment]
Hi there, no strong opinions—do whatever works best for you!

I'm not sure if you're suggesting putting a method like this in the library, but it should probably be left in user-land. I actually have a few small helper functions like this scattered around my projects.
