### ISSUE TITLE
potential feature: multi-touch capability

### ISSUE THREAD

**Issue by xinaesthete** [georgealways/lil-gui#76]
I just implemented an iPad remote-control thing with this and notice that you can't drag multiple sliders simultaneously... I reckon it'd be more fun if you could.

Glancing at the code it seems like it might be a relatively small localised change in `NumberController.js`... doesn't seem like too much else would be implicated but maybe I didn't think it through. I might try to make a PR for this if there's interest.

**Comment by georgealways** [comment]
Hi! Are you increasing the size of the sliders beyond the normal touch styles? I'm mostly surprised you can actually fit more than one finger on the panel! ;)

I agree, it could be cool! But let's weigh the complexity against demand before we merge: the slider is pretty bread and butter and I'm reluctant to change it much for a rare use case. More comments in the PR.

**Comment by xinaesthete** [comment]
For testing with your homepage, I was just zooming right in on the gui, but the thing I was really wanting it for has lots of panels in a grid layout, and once you start using it, it's not long before you start wanting to be able to tweak several simultaneously...

**Comment by georgealways** [comment]
Closing per https://github.com/georgealways/lil-gui/pull/78#issuecomment-1464917578
