### ISSUE TITLE
ALT multiplier may open Firefox's menu

### ISSUE THREAD

**Issue by Peque** [georgealways/lil-gui#8]
I don't know if this is something unavoidable (i.e.: if it would require to change ALT key to CTRL key for example), or if it could be fixed in `lil-gui`. Feel free to close if it is not possible or you would rather not change the ALT key to CTRL. :blush: 

- Open Firefox
- Start a vertical drag on a number
- Press ALT to slow down the change speed
- After releasing ALT, Firefox's top menu pops

This does not happen if you press ALT first and then start the vertical drag. :shrug: 

PS: definitely not critical for me, but since I noticed... I thought I'd open another issue. :innocent: :joy:

**Comment by georgealways** [comment]
No, thanks for pointing it out -- I'm not able to reproduce with Firefox on Mac though. What OS?

**Comment by Peque** [comment]
- Fedora 35 (Workstation Edition)
- Firefox 94.0

**Comment by georgealways** [comment]
Hm. Maybe try binding a keydown listener for Alt on window and calling preventDefault? I'd be curious if that stops it.

**Comment by Peque** [comment]
@georgealways Does your Firefox also show/hide the top menu when pressing and releasing ALT key? This behaviour, in my case, is not really related to `lil-gui`. It would happen on any other site as well.

I have tried with `event.preventDefault();` inside the callback of `document.addEventListener("keydown", onDocumentKeyDown, false);`, but it seems to have no effect. Was that what you wanted to try? It does seem to prevent other events like refresh (CTRL+R) or print (CTRL+P).

**Comment by georgealways** [comment]
Firefox doesn’t do anything with the alt key for me. And yea that’s what I
was thinking! Seems like a Firefox issue for sure.

**Comment by Peque** [comment]
@georgealways Out of curiosity, do you happen to be using Firefox 94 as well?

**Comment by georgealways** [comment]
yes
