### ISSUE TITLE
css conflict with bulma

### ISSUE THREAD

**Issue by jinfagang** [georgealways/lil-gui#80]
When I using bulma and three.js at same time, the lil-gui get very ugly.

<img width="881" alt="图片" src="https://user-images.githubusercontent.com/21303438/208707693-09818ddf-6d6a-4dfc-aa9a-33ac4d4830ad.png">

is there a way to make them hormoney to use?

**Comment by georgealways** [comment]
Right now lil-gui isn't compatible with CSS frameworks that apply global styles. You should see if Bulma offers a way to prefix or namespace selectors so their styles are only applied to elements that you choose instead of the entire page.

Slightly related to #29
