### ISSUE TITLE
allow non-linear slider mappings

### ISSUE THREAD

**Issue by kmgwalker** [georgealways/lil-gui#81]
(Apologies if this feature request has already been made and I missed it.)

Sometimes one wants a logarithmic (or approximately logarithmic, or power-law) relationship between the numeric slider position and the parameter value.  For example, the desired range might be 0.001 to 10, and one would like slider positions of 25%, 50% and 75% to correspond to values of 0.01, 0.1 and 1.

My first attempt to achieve this was to reconfigure my objects to use the logarithm of the parameter, but this has the disadvantage of the lil-gui displayed value switching from [0.001 ... 10] to [-3 ... 1].

One way to achieve this would be to allow the user to supply a pair of mutually inverse functions sliderPositionToValue() and valueToSliderPosition() (which default to a linear scaling of [0% .. 100%] to [min-value ... max-value]).  These functions would be used in setValueFromX() and updateDisplay() (in NumberController.js).

If there's a chance something like this would be implemented, I would be happy to put together a specific pull request.

(Another option would be documentation for creating custom controllers.)

**Comment by kmgwalker** [comment]
Also:

(1) Thanks for creating/maintaining lil-gui.  I think it's great.

(2) Yet another approach would be to give the user a hook to transform the numeric value before it is displayed.  E.g.

- "-2" --> "0.01" ( = 10^(-2))
- "12.34" --> "$12.34"
- "1672678497" --> "Mon Jan  2 09:54:57 2023"

**Comment by georgealways** [comment]
Hi! So the typical approach for this is to use a getter/setter to provide the mutually inverse functions you're talking about (usually using a 0-1 value as a proxy).

```js
let actualVal = 1;

const obj = { 
  get val() {
    return Math.sqrt( actualVal );
  },
  set val( val ) {
    actualVal = val * val;
  } 
};

gui.add( obj, 'val', 0, 1 );
```

I think that should achieve what you're after.

(1) Thank you!

(2) That feels like a separate feature. The original issue is about number remapping and that's more about string formatting. Maybe a feature like that could be incorporated if enough people express interest. For now you might be able to do that by overriding `NumberController.prototype.updateDisplay`

**Comment by kmgwalker** [comment]
Thanks for your quick response!  (And apologies for this delayed one.)

If I'm understanding your proposal correctly, I think it would display the sqrt-value, rather than the actual (squared) value, in the input field of the HTML <input> element.  This is very similar to the solution I already have in place.  What I was hoping for was a way to display X to the user but have the slider relate linearly to sqrt(X) (or log(X) or whatever).  Simply overriding updateDisplay also does not suffice, unless one is prepared to forgo using the <input> element as an input.

Perhaps my best option is write my own variant of the numberController class.  But it's not clear how I would add it to the main gui, since gui.add() chooses controller types based on data types.

**Comment by georgealways** [comment]
Right, the idea is to map a linear value (the one controlled by the slider) to a non-linear one. In your case the linear component is the exponent in the equation 10^n. But yes, with this approach, the controller would still display [-3, 1].

There's no plan right now to support non-linear mappings straight from the slider. I think the approach above should work for the majority of people, so for now I would recommend writing this variant as a fork of the library before worrying about how it's integrated into the core.

Thanks!
