### ISSUE TITLE
enhancement request: to allow an icon to be configured to gui/controllers

### ISSUE THREAD

**Issue by branaway** [georgealways/lil-gui#82]
So to make it end user friendlier.

Thanks

**Comment by branaway** [comment]
<img width="197" alt="Screen Shot 2023-01-03 at 12 22 44" src="https://user-images.githubusercontent.com/179513/210300152-741b43bf-337d-4784-856f-0ca38904b254.png">

Something like above.  For that to work, there should also enhance the UI layout such that 1) the the little arrow for folder open/close indications are put to the right most on the title bar, and 2) the nested layer of controls should have a much wider leading space to make the sub folders much conspicuous.  Please consider this.

**Comment by branaway** [comment]
The idea is this: icons are important for end-user facing UI. If Lil GUI would like to receive wider acceptance than just developers, it should probably  consider make it feel less cold and techie.

**Comment by georgealways** [comment]
Hi! Thanks for the suggestion. You probably won't see a feature like this in lil-gui just because developers are the primary audience and I want to keep things lean. Also this can be accomplished with CSS if it's really needed.
