### ISSUE TITLE
Is there a way to disable mouse scroll on input value sliders?

### ISSUE THREAD

**Issue by Ararana** [georgealways/lil-gui#83]
Currently if focus is put on a numerical slider, the mouse scroll wheel can be used to change it's value. Can this be disabled?

**Comment by georgealways** [comment]
Hi there—Unfortunately there's no built-in way to disable specific pieces of the number controller's functionality. I'd recommend using your fork for now, and we can discuss merging it into the lib if more requests come up. Thanks!

**Comment by georgealways** [comment]
Just to confirm, when you say focus, you mean "cursor on top of slider", correct? My intent was to make it so you could still scroll wheel by keeping your mouse on the right of the GUI.

In the interim, you could either use dipterix's fork, or comment out this line https://github.com/georgealways/lil-gui/blob/master/src/NumberController.js#L386.

(edit: Apologies @Ararana—I was conflating users here and thought the PR was yours)

**Comment by dipterix** [comment]
@Ararana I have a hack for this:

```js
// controller is a NumberController
// controller = gui.add(...)
Object.defineProperty(controller, '_hasScrollBar', {
  get: function() { return true }
});
```

In this way you can trick the controller into thinking there is a scrollbar in its parent element, hence the controller scroll effect will go away (tested on the latest lil-gui). The benefit is you don't need to change any source code.

**Comment by 1j01** [comment]
Refined @dipterix's hack to apply to all number controllers:
```js
import { NumberController } from 'lil-gui';
// Prevent accidentally changing settings while scrolling
// (see https://github.com/georgealways/lil-gui/issues/83)
Object.defineProperty(NumberController.prototype, '_hasScrollBar', { get: () => true });
```
