### ISSUE TITLE
autoplace issues

### ISSUE THREAD

**Issue by branaway** [georgealways/lil-gui#85]
I have two qestions:

1) the autoPlace put the menu top right corner when the screen is in landscape, such as in a PC browser. It however goes to the bottom left when the screen is in portrait mode such as in a mobile browser. 

2) I'd like to place the menu at the top left corner, by hacking the css this way:

		.lil-gui.autoPlace {
			max-height: 100%;
  			position: fixed;
  			top: 0;
			left: 5px;
			z-index: 1001;
		} 

The max-height gives trouble and renders the menu using 100% of the height, no matter how little my menu item list is.  It does not auto-shrink to the most fit height anymore. 

Any help is appreciated!

**Comment by georgealways** [comment]
autoPlace will always be placed on the top right, on both mobile and desktop (https://lil-gui.georgealways.com/examples/basic/). Sounds like you have some other external CSS on the page affecting the GUI.

You'll need to set `right: auto` to disable the default autoPlace positioning. It sounds like you might have something setting `bottom: 0` as well, so setting it that to auto may stop the GUI from being full height.

Hope that helps.

**Comment by branaway** [comment]
works great! thanks a lot!
