### ISSUE TITLE
Range slider controller

### ISSUE THREAD

**Issue by antlii** [georgealways/lil-gui#87]
Is there any chance of getting a range values controller in near future?
Something like this:
<img width="496" alt="image" src="https://user-images.githubusercontent.com/52974033/216633164-7b60f50c-54f5-4637-8ebc-f9c83544eaa2.png">

Will be grateful for any advice or help.

ps.
George, a big thanks to you for the awesome library! ❤️

**Comment by georgealways** [comment]
Hi! So this would be a great use case for a custom controller API, but unfortunately I don't think that's something I can get to very soon. 

For now, my best advice for anyone looking to make more complex controllers like this is to use a library like TweakPane, which already has support for plugins.

I appreciate the kind words!

**Comment by antlii** [comment]
@georgealways Thanks for the great suggestion, George! It looks impressive, I think it's a great solution for my case. Kudos to you ❤️
