### ISSUE TITLE
NumpadEnter doesn't blur input fields

### ISSUE THREAD

**Issue by Pickleheaded** [georgealways/lil-gui#89]
HI,
Should pressing the enter key on a number controller invoke onFinishChange()? 

I see there is the following

> const onKeyDown = e => {
> 			if ( e.code === 'Enter' ) {
> 				this.$input.blur();
> 			}
> 			if ( e.code === 'ArrowUp' ) {
> 				e.preventDefault();
> 				increment( this._step * this._arrowKeyMultiplier( e ) );
> 			}
> 			if ( e.code === 'ArrowDown' ) {
> 				e.preventDefault();
> 				increment( this._step * this._arrowKeyMultiplier( e ) * -1 );
> 			}
> 		};

Thank you!

**Comment by Pickleheaded** [comment]
Ok, I tried this on a few different keyboards and suddenly realised nothing was happening because I was inputting data using the number keypad and pressing the number key pad 'Enter Key'.

Could const onKeyDown be changed to include NumpadEnter as below?

> const onKeyDown = e => {
> 			if ( e.code === 'Enter' || e.code === 'NumpadEnter' ) {
> 				this.$input.blur();
> 			}
> 			if ( e.code === 'ArrowUp' ) {
> 				e.preventDefault();
> 				increment( this._step * this._arrowKeyMultiplier( e ) );
> 			}
> 			if ( e.code === 'ArrowDown' ) {
> 				e.preventDefault();
> 				increment( this._step * this._arrowKeyMultiplier( e ) * -1 );
> 			}
> 		};
> 

Thank you!

**Comment by georgealways** [comment]
Good catch. Looking at [this](https://www.toptal.com/developers/keycode), it seems like we could use `e.key === 'Enter'` to capture both. Either way, numpad enter should work here—thank you!

**Comment by georgealways** [comment]
Hey! This should be fixed as of 0.18.2
