### ISSUE TITLE
Nested Folder Indent

### ISSUE THREAD

**Issue by Pickleheaded** [georgealways/lil-gui#92]
Hi
Is it possible to have an option added so that the titles and arrows of nested folders could be a different class so they can be modified  independently of a normal folder. 

Would be nice where you have multiple nested folders if the class could be adjusted to give a definitive look.

In the attached image, 'Run 1' to 'Run 4' are nested folders of 'Staircase Runs' but would be nice to indent them slightly. Nested folder indent is perfect for the contents.
![2023-02-24](https://user-images.githubusercontent.com/65015665/221200139-c43c3bf0-54ad-48d4-af63-790fcfc4cf56.png)

**Comment by georgealways** [comment]
Hi, you can target a nested folder with a selector like this:

```css
.lil-gui .lil-gui .lil-gui {

}
```

Weird looking, but it's basically saying "a lil gui with two lil gui's above it"—that's actually how nested folders are targeted internally.

Looking cool, curious to see how you style them.

**Comment by Pickleheaded** [comment]
That's great thanks!

**Comment by Pickleheaded** [comment]
Just tried your suggestion and worked great!
