### ISSUE TITLE
Question about referencing a menu controller

### ISSUE THREAD

**Issue by Pickleheaded** [georgealways/lil-gui#98]
Is it possible to set a value of an input box in lil-gui from an input box created when the page is first loaded?

**Comment by georgealways** [comment]
I'm not quite sure what you're asking, but you might be looking for `controller.setValue( v )`.

**Comment by Pickleheaded** [comment]
Hi, 
I added and event listener to the input box as below

` let theInput = document.getElementById('input_8');
  theInput.addEventListener('blur', () => { gui.controller = theInput.value;});`

With listen() added to the controller, this now updates the value of the controller perfectly.

Is there a way with the new value set of calling the lil-gui controllers onFinishedChange event?

**Comment by Pickleheaded** [comment]
Ok, so I partially solved my particular problem.

To prevent unwanted redraws to the scene, I use onFinishedChange within lil-gui which works perfectly.

However, I needed to create a multiple step form to guides newer users through the design process, but still allow advanced users to be able to access the hundreds of settings stored within  lil-gui. 

The target was to ensure both the step form values and lil-gui values remain synced and both update the three.js scene.

So my solution was to add a Boolean to the lil-gui onFinishedChange event and the blur eventListener of the form elements. 

The renderer within my code then looks for this value and updates if this value is true.


Next challenge a better way to handle the eventListeners rather than have a listener per form element

**Comment by georgealways** [comment]
Glad to hear you found a solution. Cheers -g
